executors:
  with_db:
    docker:
      - image: cimg/ruby:2.7.1
        environment:
          DB_HOST: 127.0.0.1
          RAILS_ENV: test
          BUNDLER_VERSION: 2.1.4
      - image: circleci/mysql:8.0.18-ram
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: "test_db"
        # MySQL 8.0.4移行の認証プラグインを変更する
        command: mysqld --default-authentication-plugin=mysql_native_password
    working_directory: ~/repo

version: 2.1
jobs:
  setup_test_rspec:
    executor: with_db
    steps:
      - checkout
      - run:
          name: gemのインストール
          command: |
            sudo gem update --system \
            gem install bundler -v 2.1.4 \
            bundle install
      - run:
          name: データベースの起動を待機
          command: |
            dockerize -wait \
            tcp://${DB_HOST}:3306 -timeout 120s
      - run:
          name: データベースのセットアップ
          command: bundle exec rake db:schema:load --trace
      - run:
          name: RSpecを実行
          command: bundle exec rspec

workflows:
  version: 2
  build_test:
    jobs:
      - setup_test_rspec
